server:
  port: 8081
spring:
  cloud:
    config:
      server: 
        git:
          default-label: main
          uri: https://github.com/Klonoire/smart-java-poc
          search-paths: config-data
  application:
    name: config-service